name: Append data data every day at 00:10

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "10 0 * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Append new data
        run: |-
          curl \
            -H "Authorization: Bearer $TOKEN" \
            -X POST \
              -d url=$CSV_URL \
              -d mode='append' \
              -d name='events' \
              https://api.tinybird.co/v0/datasources
